# Generated by Django 4.2.7 on 2023-12-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Responsibility',
        ),
    ]
