# Generated by Django 4.2.7 on 2023-12-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='remote_uuid',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='is_response',
            field=models.BooleanField(default=False),
        ),
    ]
