# Generated by Django 4.2.7 on 2023-12-10 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='assistant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='assistants.assistant'),
        ),
    ]
