# Generated by Django 4.2.7 on 2023-12-12 00:13

import assistants.models.message
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0002_thread_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('user', 'user'), ('assistant', 'assistant'), ('notification', 'notification'), ('call', 'call')], default=assistants.models.message.Message.get_default_type),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('arguments', models.JSONField()),
                ('remote_uuid', models.TextField()),
                ('output', models.TextField(blank=True, default=None, null=True)),
                ('func', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='assistants.function')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='assistants.message')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', utils.models.Manager()),
            ],
        ),
    ]
