# Generated by Django 4.2.7 on 2023-12-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistants', '0003_message_type_alter_message_content_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='question',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
