# Generated by Django 4.2.7 on 2023-12-09 17:25

from django.db import migrations, models
import django.utils.timezone
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('file', models.FileField(upload_to=files.models.File.file_upload_location)),
                ('size', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', files.models.FileManager()),
            ],
        ),
    ]
